[package]
	name = "class_file"
	version = "0.1.0"
	edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
	anyhow = "1.0.75"

	zip = "0.6.0"

	itertools = "0.11.0"
